### ISSUE TITLE
#horovod# data Size does not match 

### ISSUE THREAD

**Issue by anthony123** [tensorpack/benchmarks#2]
I modified  my code  to run it on cifar10, the error trace tells me the size mismatched(one is as twice as the other). the errors are as follows:
![sizeerror](https://user-images.githubusercontent.com/4050099/36674732-dcf21796-1b41-11e8-8f86-c9fa035fdff1.png)

here are my codes: 
[code1](https://github.com/anthony123/learnit/blob/master/server_data.py)
[code2](https://github.com/anthony123/learnit/blob/master/cifar10-sparse-densenet-bc-horovod.py)

I run it as(I have two gpus on my local machine):
`python3 server_data.py --batch 32`
`mpirun -np 2 --output-filename test.log python3 cifar10-sparse-densenet-bc-horovod.py --batch 32 --gpu=0,1`

any suggestion would be appreciated!

**Comment by ppwwyyxx** [comment]
For small dataset like cifar you don't need a separate process to provide data. You can just put the dataloader in the training code and use `QueueInput` like any of the existing tensorpack examples.

`ZMQInput` requires accurate type information. Here your dataflow is probably float64, because your mean and std are float64. However the model declares the input as float32.

**Comment by anthony123** [comment]
@ppwwyyxx  
after change my data type to np.float32, and thing goes well

And I have another problem, in the line 44-45 of  imagenet-resnet-horovod.py file: 

```
if self._loss_scale != 1.0:
     self.cost = self.cost * self._loss_scale
```
`self.cost` does not define before, which caused a problem, by now i just commented out. 
Maybe it it a bug or how can i use it in my code?

**Comment by ppwwyyxx** [comment]
If you saw error, post them.
`self.cost` was defined in the original code by the `super()` call.

**Comment by anthony123** [comment]
@ppwwyyxx 
o, i see. I move the codes after where i defined my self.cost, which should  solve my problem.
Thanks a lot.
