### ISSUE TITLE
Some questions about dataflow

### ISSUE THREAD

**Issue by megazone87** [tensorpack/benchmarks#3]
I have read the doc of tensorpack, but found that the dataflow is confusing me as follows:

1. Why using 'lmdb' format to keep serialize data, rather than TFRecord, while the latter has native TF api support?

2. According to this [benchmark](https://github.com/tensorpack/benchmarks/tree/master/ImageNet), tf.data is probably faster than dataflow, is it?

**Comment by ppwwyyxx** [comment]
1. Having native support means you need to read it into the graph, not python.

2. It is. But dataflow is in python and easier to customize and debug. The speed of dataflow is enough in almost all cases I've ever met. 

These are discussed in the docs: http://tensorpack.readthedocs.io/tutorial/input-source.html#python-reader-or-tf-reader.
