### ISSUE TITLE
ResNet-Horovod example doesn't use DistributedOptimizer?

### ISSUE THREAD

**Issue by npow** [tensorpack/benchmarks#4]
I'm looking at the `ResNet-Horovod` example, and it doesn't use the horovod `DistributedOptimizer` which is mentioned in the horovod docs. Is it not necessary?

```
# Add Horovod Distributed Optimizer
opt = hvd.DistributedOptimizer(opt)
```

**Comment by ppwwyyxx** [comment]
It is not necessary.

**Comment by npow** [comment]
Ok, I see the gradients are averaged via `HorovodTrainer`.
