### ISSUE TITLE
What the performance of serve_data.py utul?

### ISSUE THREAD

**Issue by glkclass** [tensorpack/benchmarks#6]
I have a poor scaling results for even two workers using Horovod on my environment, want to locate the reason. Hence the question: what are the typical (on your environment)  results of running 
`./serve-data.py --data ~/data/imagenet/ --batch 32 --benchmark` ?

**Comment by ppwwyyxx** [comment]
That depends on many factors. I typically see 3k ~ 5k total images per sec.

**Comment by glkclass** [comment]
That's means 90 - 160 iter/sec with batch 32. I see 50 - 70 it/sec at my env. And have significant performance degradation: one workers runs 10 it/sec while two workers run twice slower: 5 it/sec. Seems the problem something else. Will run more experiments...
Thanks for answer.

**Comment by ppwwyyxx** [comment]
What do u mean by "workers"?

**Comment by glkclass** [comment]
Two workers = 2 GPU running using Horovod approach.(Resnet-Horovod benchmark). Or two towers as named in log file.

**Comment by glkclass** [comment]
For now, closing the issue. With `serve_data.py` performance all seems clear. Regarding poor distributed mode performance - will continue looking into the issue...
